package zhab.util.appresp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-12T10:31:18.477+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "urn:DefaultNamespace", name = "Provider")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Provider {

    @WebMethod(operationName = "APPLY", action = "APPLY")
    @WebResult(name = "APPLYReturn", targetNamespace = "urn:DefaultNamespace", partName = "APPLYReturn")
    public java.lang.String apply(
        @WebParam(partName = "PROVIDERINFO", name = "PROVIDERINFO")
        java.lang.String providerinfo,
        @WebParam(partName = "ZGID", name = "ZGID")
        java.lang.String zgid,
        @WebParam(partName = "ZGCLRID", name = "ZGCLRID")
        java.lang.String zgclrid,
        @WebParam(partName = "ZGCLR", name = "ZGCLR")
        java.lang.String zgclr,
        @WebParam(partName = "CLRTYPE", name = "CLRTYPE")
        java.lang.String clrtype,
        @WebParam(partName = "ZGNEIRONG", name = "ZGNEIRONG")
        java.lang.String zgneirong,
        @WebParam(partName = "ZGPIC", name = "ZGPIC")
        java.lang.String zgpic,
        @WebParam(partName = "ZGPICNAME", name = "ZGPICNAME")
        java.lang.String zgpicname,
        @WebParam(partName = "ISOVER", name = "ISOVER")
        java.lang.String isover
    );
}
